name: "first-workflow"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      - dev
      - qa

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: "setup node js in VM"
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: run ESint in app
        run: npm run lint

      - name: run test cases
        run: npm run test

      - name: Make React build
        run: npm run build
